// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace UserRegisterSpecs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("Finding Users", Description="\tIn order to a keep track of my members\r\n\tAs a club manager\r\n\tI want to know who " +
        "has already joined", SourceFile="FindingUsers.feature", SourceLine=0)]
    public partial class FindingUsersFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "FindingUsers.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Finding Users", "\tIn order to a keep track of my members\r\n\tAs a club manager\r\n\tI want to know who " +
                    "has already joined", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("List all users", SourceLine=5)]
        public virtual void ListAllUsers()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("List all users", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Password",
                        "Telephone Number",
                        "Street",
                        "City",
                        "Country"});
            table1.AddRow(new string[] {
                        "Jack Sparrow",
                        "pirat1s",
                        "07568953571",
                        "10 Main Street",
                        "Nassau",
                        "Bahamas"});
            table1.AddRow(new string[] {
                        "Jack Rackham",
                        "pirat2s",
                        "07568953572",
                        "12 Main Street",
                        "Nassau",
                        "Bahamas"});
            table1.AddRow(new string[] {
                        "Charles Vane",
                        "pirat3s",
                        "07568953573",
                        "14 Main Street",
                        "Nassau",
                        "Bahamas"});
#line 7
 testRunner.Given("the following registered users", ((string)(null)), table1, "Given ");
#line 12
 testRunner.When("I list all of the registered users", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table2.AddRow(new string[] {
                        "Jack Sparrow"});
            table2.AddRow(new string[] {
                        "Jack Rackham"});
            table2.AddRow(new string[] {
                        "Charles Vane"});
#line 13
 testRunner.Then("I should obtain the following users:", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Find a user by name", SourceLine=18)]
        public virtual void FindAUserByName()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find a user by name", ((string[])(null)));
#line 19
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Password",
                        "Telephone Number",
                        "Street",
                        "City",
                        "Country"});
            table3.AddRow(new string[] {
                        "Jack Sparrow",
                        "pirat1s",
                        "07568953571",
                        "10 Main Street",
                        "Nassau",
                        "Bahamas"});
            table3.AddRow(new string[] {
                        "Jack Rackham",
                        "pirat2s",
                        "07568953572",
                        "12 Main Street",
                        "Nassau",
                        "Bahamas"});
            table3.AddRow(new string[] {
                        "Charles Vane",
                        "pirat3s",
                        "07568953573",
                        "14 Main Street",
                        "Nassau",
                        "Bahamas"});
#line 20
 testRunner.Given("the following registered users", ((string)(null)), table3, "Given ");
#line 25
 testRunner.When("I search for registered users named \"Jack Rackham\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table4.AddRow(new string[] {
                        "Jack Rackham"});
#line 26
 testRunner.Then("I should obtain the following user:", ((string)(null)), table4, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Find a user by id", SourceLine=29)]
        public virtual void FindAUserById()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find a user by id", ((string[])(null)));
#line 30
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Password",
                        "Telephone Number",
                        "Street",
                        "City",
                        "Country"});
            table5.AddRow(new string[] {
                        "Jack Rackham",
                        "pirat3s",
                        "07568953571",
                        "10 Main Street",
                        "Nassau",
                        "Bahamas"});
#line 31
 testRunner.Given("a new user", ((string)(null)), table5, "Given ");
#line 34
 testRunner.And("he has registered online", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 35
 testRunner.When("I search for a registered user with the returned Id value", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table6.AddRow(new string[] {
                        "Jack Rackham"});
#line 36
 testRunner.Then("I should obtain the following user:", ((string)(null)), table6, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
